import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { DRACOLoader } from 'three/examples/jsm/loaders/DRACOLoader.js';

// Loader/cache for the 21 part archetype models (draco-compressed GLBs in
// public/models/, generated by the site owner in Claude Design from our
// style-guide prompts — original OBJ sources kept in the design tool).
//
// Model conventions this module relies on:
// - Node names are semantic; any node named blades_N is a fan blade set that
//   the scene spins. Geometry arrives in absolute coordinates (nodes carry no
//   transforms), so blade geometry is re-centered once at load to make
//   rotation-in-place possible.
// - Material names are semantic (purple_glow, cyan_glow, glass, copper,
//   brushed_metal, pcb_dark, rubber_black, ...) and drive restyling into the
//   site's PBR look — glow materials become emissive-style basics that the
//   scene's RGB cycler animates, glass becomes the shared tempered-glass
//   physical material.

export type ModelName =
  | 'gpu-flagship' | 'gpu-highend' | 'gpu-midrange' | 'gpu-compact' | 'gpu-blower'
  | 'case-fulltower' | 'case-midtower' | 'case-airflow' | 'case-compact'
  | 'cooler-air-small' | 'cooler-air-big' | 'cooler-aio-240' | 'cooler-aio-360'
  | 'motherboard-atx' | 'motherboard-matx'
  | 'fan-rgb-120' | 'ram-rgb' | 'psu-atx' | 'cpu-chip' | 'ssd-25' | 'ssd-nvme';

export interface LoadedModel {
  /** Source scene — clone before adding to a live scene graph. */
  scene: THREE.Group;
  /** Bounding-box size of the source model, in its native units (mm). */
  size: THREE.Vector3;
  /** Restyled glow materials (shared by all clones) for the RGB cycler. */
  glowMats: THREE.MeshBasicMaterial[];
}

export interface ModelInstance {
  group: THREE.Group;
  /** Blade-set nodes plus the local axis each should spin around. */
  spinners: { obj: THREE.Object3D; axis: 'x' | 'y' | 'z' }[];
}

const ACCENT = 0x6c63ff;
const CYAN = 0x00d4ff;

let gltfLoader: GLTFLoader | null = null;
function getLoader(): GLTFLoader {
  if (!gltfLoader) {
    gltfLoader = new GLTFLoader();
    const draco = new DRACOLoader();
    draco.setDecoderPath('/draco/');
    gltfLoader.setDRACOLoader(draco);
  }
  return gltfLoader;
}

function makeGlass(): THREE.MeshPhysicalMaterial {
  return new THREE.MeshPhysicalMaterial({
    color: 0x99bbff, roughness: 0.04, metalness: 0, transparent: true, opacity: 0.05,
    envMapIntensity: 0.8, side: THREE.DoubleSide, depthWrite: false,
  });
}

/** Restyle a GLB material into the site's look, keyed off its semantic name.
 * Returns a replacement material, or null to keep (a possibly mutated)
 * original. */
function restyleMaterial(mat: THREE.MeshStandardMaterial, glowMats: THREE.MeshBasicMaterial[]): THREE.Material | null {
  const name = (mat.name || '').toLowerCase();
  if (name.includes('glow')) {
    const basic = new THREE.MeshBasicMaterial({ color: name.includes('cyan') ? CYAN : ACCENT });
    glowMats.push(basic);
    return basic;
  }
  if (name.includes('glass')) return makeGlass();
  if (name.includes('copper') || name.includes('brushed') || name.includes('silver') || name.includes('gold')) {
    mat.metalness = 0.85;
    mat.roughness = 0.32;
    mat.envMapIntensity = 1.1;
    return null;
  }
  if (name.includes('pcb')) {
    mat.metalness = 0.25;
    mat.roughness = 0.6;
    mat.envMapIntensity = 0.6;
    return null;
  }
  if (name.includes('rubber')) {
    mat.metalness = 0.05;
    mat.roughness = 0.85;
    return null;
  }
  // gunmetal_plastic / panel_black / anything else: dark plastic
  mat.metalness = 0.25;
  mat.roughness = 0.55;
  mat.envMapIntensity = 0.7;
  return null;
}

/** Geometry arrives in absolute coordinates; give this node a real local
 * origin at its bbox center so it can be rotated in place (fan blades). */
function recenterNode(obj: THREE.Object3D) {
  const mesh = obj as THREE.Mesh;
  if (!mesh.geometry) return;
  mesh.geometry.computeBoundingBox();
  const center = mesh.geometry.boundingBox!.getCenter(new THREE.Vector3());
  mesh.geometry.translate(-center.x, -center.y, -center.z);
  mesh.position.add(center);
}

/** Thinnest local dimension of a (recentered) flat disc = its spin axis. */
function thinnestAxis(obj: THREE.Object3D): 'x' | 'y' | 'z' {
  const mesh = obj as THREE.Mesh;
  if (!mesh.geometry) return 'z';
  mesh.geometry.computeBoundingBox();
  const size = mesh.geometry.boundingBox!.getSize(new THREE.Vector3());
  if (size.x <= size.y && size.x <= size.z) return 'x';
  if (size.y <= size.x && size.y <= size.z) return 'y';
  return 'z';
}

const cache = new Map<ModelName, Promise<LoadedModel>>();

export function loadModel(name: ModelName): Promise<LoadedModel> {
  let entry = cache.get(name);
  if (!entry) {
    entry = getLoader().loadAsync(`/models/${name}.glb`).then((gltf) => {
      const scene = gltf.scene;
      const glowMats: THREE.MeshBasicMaterial[] = [];
      const replaced = new Map<THREE.Material, THREE.Material>();
      scene.traverse((obj) => {
        const mesh = obj as THREE.Mesh;
        if (obj.name.startsWith('blades')) recenterNode(obj);
        if (!mesh.isMesh) return;
        mesh.castShadow = true;
        const mats = Array.isArray(mesh.material) ? mesh.material : [mesh.material];
        const out = mats.map((m) => {
          let r = replaced.get(m);
          if (!r) {
            r = restyleMaterial(m as THREE.MeshStandardMaterial, glowMats) ?? m;
            replaced.set(m, r);
          }
          return r;
        });
        mesh.material = Array.isArray(mesh.material) ? out : out[0];
      });
      const size = new THREE.Box3().setFromObject(scene).getSize(new THREE.Vector3());
      return { scene, size, glowMats };
    });
    cache.set(name, entry);
  }
  return entry;
}

/** Clone for scene use (geometry + restyled materials stay shared). */
export function instantiateModel(model: LoadedModel): ModelInstance {
  const group = model.scene.clone(true);
  const spinners: ModelInstance['spinners'] = [];
  group.traverse((obj) => {
    if (obj.name.startsWith('blades')) spinners.push({ obj, axis: thinnestAxis(obj) });
  });
  return { group, spinners };
}
