import { mkdir, rm } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createCaptionRenderAdapter } from "./captionRender.ts";
import { createElevenLabsTtsAdapter, elevenLabsTtsConfigFromEnv } from "./elevenLabsTts.ts";
import { createMotionCompositorAdapter } from "./motionCompositor.ts";
import { RenderAdapterRegistry, renderPlatformPlan } from "./rendering.ts";
import type { PlatformProductionPlan, ProductionPlanPackage, ProductionTask } from "./types.ts";
import { createDeterministicUiRenderAdapter } from "./uiRender/deterministicUiRenderAdapter.ts";

const here = dirname(fileURLToPath(import.meta.url));
const outputDir = join(here, "..", "..", "render-output", "mp4-smoke");
const baseUrl = process.env.SPECSMITH_RENDER_BASE_URL ?? "http://localhost:5178";

function uiTask(taskId: string, captureType: "static" | "sequence"): ProductionTask {
  return {
    taskId,
    capability: "deterministic-ui-render",
    sourceBeat: null,
    purpose: "Render the real SpecSmith RTX 4080 Super vs RTX 4080 comparison.",
    inputRequirements: ["Real SpecSmith Compare UI only."],
    outputRequirements: ["1080x1920 factual SpecSmith UI capture."],
    uiRenderState: {
      state: {
        surface: "compare",
        gpuA: "rtx4080s",
        cpuA: "r9-9950x3d",
        gpuB: "rtx4080",
        cpuB: "r9-9950x3d",
        resolution: "1440p",
        preset: "high",
      },
      captureType,
    },
  };
}

function smokePlan(): { pkg: ProductionPlanPackage; plan: PlatformProductionPlan } {
  const visual1 = uiTask("youtube-shorts-smoke-visual-1", "static");
  const visual2 = uiTask("youtube-shorts-smoke-visual-2", "sequence");
  const visual3 = uiTask("youtube-shorts-smoke-visual-3", "static");

  const voice: ProductionTask = {
    taskId: "youtube-shorts-smoke-voice",
    capability: "text-to-speech",
    sourceBeat: null,
    purpose: "Generate real narration for the compositor smoke video.",
    inputRequirements: [
      "RTX 4080 Super versus RTX 4080. Same CPU, same settings. SpecSmith shows which one wins.",
    ],
    outputRequirements: ["Natural narration; preserve hardware names exactly."],
  };

  const captions: ProductionTask = {
    taskId: "youtube-shorts-smoke-captions",
    capability: "caption-render",
    sourceBeat: null,
    purpose: "Render deterministic short-form captions.",
    inputRequirements: ["RTX 4080 SUPER VS RTX 4080", "SAME CPU. SAME SETTINGS.", "SEE THE RESULT"],
    outputRequirements: ["Keep captions inside short-form safe areas."],
  };
  (captions as ProductionTask & { captionRenderState?: unknown }).captionRenderState = {
    durationSeconds: 8,
    cues: [
      { startSecond: 0, endSecond: 2.5, text: "RTX 4080 SUPER VS RTX 4080" },
      { startSecond: 2.5, endSecond: 5.5, text: "SAME CPU. SAME SETTINGS." },
      { startSecond: 5.5, endSecond: 8, text: "SEE THE SPECSMITH RESULT" },
    ],
  };

  const compose: ProductionTask = {
    taskId: "youtube-shorts-smoke-compose",
    capability: "motion-compositor",
    sourceBeat: null,
    purpose: "Produce one real 1080x1920 H.264/AAC MP4 from real UI, real TTS, and timed captions.",
    inputRequirements: [visual1.taskId, visual2.taskId, visual3.taskId, voice.taskId, captions.taskId],
    outputRequirements: ["Real video/mp4 artifact, not a dry-run placeholder."],
  };
  (compose as ProductionTask & { compositorState?: unknown }).compositorState = {
    durationSeconds: 8,
    fps: 30,
    visualTimeline: [
      { visualTaskId: visual1.taskId, startSecond: 0, endSecond: 2.5 },
      { visualTaskId: visual2.taskId, startSecond: 2.5, endSecond: 5.5 },
      { visualTaskId: visual3.taskId, startSecond: 5.5, endSecond: 8 },
    ],
    voiceTaskId: voice.taskId,
    captionTaskId: captions.taskId,
  };

  const tasks = [visual1, visual2, visual3, voice, captions, compose];
  const plan: PlatformProductionPlan = {
    platform: "youtube-shorts",
    targetDurationSeconds: 8,
    tasks,
    renderOrder: tasks.map((task) => task.taskId),
    qualityChecks: [
      "Final artifact is a real 1080x1920 MP4.",
      "All product UI is deterministic real SpecSmith UI.",
      "Narration is generated by the configured ElevenLabs voice.",
      "Captions follow explicit cue timing.",
    ],
  };
  return {
    pkg: {
      packageId: "mp4-smoke",
      ideaId: "compare-rtx4080s-rtx4080",
      campaignId: "mp4-smoke",
      platforms: [plan],
    },
    plan,
  };
}

async function main(): Promise<void> {
  const tts = elevenLabsTtsConfigFromEnv();
  if (!tts) {
    throw new Error("ELEVENLABS_API_KEY is required for the real MP4 smoke render; refusing to replace narration with a fake placeholder.");
  }

  await rm(outputDir, { recursive: true, force: true });
  await mkdir(outputDir, { recursive: true });
  const registry = new RenderAdapterRegistry()
    .register(createDeterministicUiRenderAdapter({ baseUrl, outputDir: join(outputDir, "ui") }))
    .register(createElevenLabsTtsAdapter({ config: tts, outputDir: join(outputDir, "audio") }))
    .register(createCaptionRenderAdapter({ outputDir: join(outputDir, "captions") }))
    .register(createMotionCompositorAdapter({
      outputDir,
      ffmpegPath: process.env.SPECSMITH_FFMPEG_PATH,
      ffprobePath: process.env.SPECSMITH_FFPROBE_PATH,
    }));

  const { pkg, plan } = smokePlan();
  console.log(`Rendering real MP4 smoke against ${baseUrl} with voice ${tts.voiceId}.`);
  const result = await renderPlatformPlan(pkg, plan, registry, { maxAttemptsPerCapability: 1 });
  if (result.status !== "succeeded" || result.finalArtifacts.length !== 1) {
    for (const task of result.taskResults) {
      if (task.status !== "succeeded") console.error(`${task.taskId}: ${task.status} ${task.error ?? ""}`);
    }
    throw new Error("Real MP4 smoke render failed.");
  }
  const final = result.finalArtifacts[0];
  if (final.mimeType !== "video/mp4" || final.uri.startsWith("dry-run://")) {
    throw new Error(`Compositor returned ${final.mimeType} at ${final.uri}, not a real MP4.`);
  }
  console.log("Real MP4 compositor smoke succeeded.");
  console.log(`Output: ${final.uri}`);
  console.log(`Metadata: ${JSON.stringify(final.metadata)}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
