// MASTER #4 — Language and question intelligence (section 4).
//
// Two kinds of phrase live here and they must never be confused:
//
//   OBSERVED   — a real person actually typed or said this, and a signal proves it.
//   GENERATED  — the system wrote this paraphrase to vary creative copy.
//
// A generated paraphrase is useful. Presenting one as user language is a
// fabricated observation, so the two are different types with no path from the
// second to the first. `asObserved` exists only to make that attempt fail loudly.

import type { AudienceSignal, AudienceSignalBundle } from "./signals.ts";
import type { AudienceIntent, ExpertiseLevel, JobToBeDone } from "./model.ts";

export type PhraseOrigin = "observed" | "generated";

/** A phrase a real person actually used, tied to the signal that saw it. */
export interface ObservedPhrase {
  readonly origin: "observed";
  readonly phrase: string;
  readonly normalizedIntent: AudienceIntent;
  readonly terminology: readonly string[];
  readonly expertiseImplication: ExpertiseLevel | "unknown";
  readonly ambiguity: string | null;
  readonly associatedJob: JobToBeDone | null;
  readonly signalId: string;
  readonly sourceReference: string;
  /** Only when a collector genuinely counted. Never inferred from one sighting. */
  readonly frequency: number | null;
  readonly observedAt: string;
}

/** A phrase the system invented. Useful for variation; never evidence. */
export interface GeneratedPhrase {
  readonly origin: "generated";
  readonly phrase: string;
  readonly derivedFromPhrase: string | null;
  readonly rationale: string;
  /** Always null. A generated phrase has no frequency because nobody said it. */
  readonly frequency: null;
}

export type Phrase = ObservedPhrase | GeneratedPhrase;

export class LanguageProvenanceError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "LanguageProvenanceError";
  }
}

/**
 * The one-way door.
 *
 * Anything that wants to treat a phrase as user language must come through
 * here, and a generated phrase is refused by name. There is no flag, option or
 * override that turns a paraphrase into an observation.
 */
export function asObserved(phrase: Phrase): ObservedPhrase {
  if (phrase.origin === "generated") {
    throw new LanguageProvenanceError(
      `"${phrase.phrase}" was generated by the system, not observed from a user. ` +
        "A paraphrase may vary creative copy, but it can never be represented as the language an audience actually used.",
    );
  }
  return phrase;
}

/** Extract the observed phrases from a signal bundle. */
export function observedPhrases(bundle: AudienceSignalBundle): readonly ObservedPhrase[] {
  const phrases: ObservedPhrase[] = [];
  for (const signal of bundle.signals) {
    if (!signal.dimensions.includes("language.phrase")) continue;
    phrases.push(toObservedPhrase(signal));
  }
  return phrases.sort((a, b) => a.phrase.localeCompare(b.phrase));
}

function toObservedPhrase(signal: AudienceSignal): ObservedPhrase {
  return {
    origin: "observed",
    phrase: signal.observation,
    normalizedIntent: normalizeIntent(signal.observation),
    terminology: extractTerminology(signal.observation),
    expertiseImplication: expertiseFromPhrasing(signal.observation),
    ambiguity: detectAmbiguity(signal.observation),
    associatedJob: jobFromPhrasing(signal.observation),
    signalId: signal.signalId,
    sourceReference: signal.sourceReference,
    // Sample size is the only honest frequency, and it is often null.
    frequency: signal.sampleSize,
    observedAt: signal.observedAt ?? signal.capturedAt,
  };
}

/**
 * Classify what a phrase is trying to accomplish.
 *
 * Pattern matching on real phrasing, not a model call — this must be
 * deterministic and explainable. Where nothing matches, the intent falls to
 * `informational` rather than being guessed more specifically.
 */
export function normalizeIntent(phrase: string): AudienceIntent {
  const text = phrase.toLowerCase();
  if (/\b(vs|versus|or|better than|compared to|difference between)\b/.test(text)) return "comparison";
  if (/\b(why is|why does|fix|problem|issue|stutter|crash|low fps|not working)\b/.test(text)) return "troubleshooting";
  if (/\b(worth|should i buy|should i upgrade|is it worth|good deal)\b/.test(text)) return "purchasing-research";
  if (/\b(settings|configure|setup|set up|overclock|tune)\b/.test(text)) return "configuration";
  if (/\b(will|can|does .* fit|compatible|bottleneck)\b/.test(text)) return "validation";
  if (/\b(what is|what does|how does|explain|mean)\b/.test(text)) return "informational";
  if (/\b(best|recommend|which should)\b/.test(text)) return "discovery";
  return "informational";
}

/** Hardware terminology present in the phrase, for the terminology policy. */
export function extractTerminology(phrase: string): readonly string[] {
  const terms = [
    "vram", "gpu", "cpu", "fps", "psu", "ram", "ssd", "nvme", "tdp", "bottleneck",
    "socket", "chipset", "motherboard", "ray tracing", "dlss", "fsr", "frame gen",
    "1080p", "1440p", "4k", "overclock", "thermal throttle", "pcie",
  ];
  const text = phrase.toLowerCase();
  return terms.filter((term) => text.includes(term));
}

/**
 * What the phrasing suggests about expertise.
 *
 * A supported inference at best — people borrow vocabulary they do not
 * understand, and `unknown` is returned whenever the phrasing is neutral.
 */
export function expertiseFromPhrasing(phrase: string): ExpertiseLevel | "unknown" {
  const text = phrase.toLowerCase();
  if (/\b(what is|what does|explain|i'm new|beginner|first pc|dont know|don't know)\b/.test(text)) return "beginner";
  if (/\b(undervolt|vrm|timings|subtimings|pcie lanes|infinity fabric|curve optimizer)\b/.test(text)) return "advanced";
  return "unknown";
}

/** Phrasing that could mean two different things, which creative must resolve. */
export function detectAmbiguity(phrase: string): string | null {
  const text = phrase.toLowerCase();
  if (/\bbottleneck\b/.test(text)) {
    return "\"Bottleneck\" is used both for a real frame-rate limit and as a general worry about mismatched parts; the two need different answers.";
  }
  if (/\benough\b/.test(text)) {
    return "\"Enough\" is undefined without a resolution, a target frame rate and a game.";
  }
  if (/\bgood\b/.test(text) && !/\bgood deal\b/.test(text)) {
    return "\"Good\" has no fixed meaning here; it may mean fast, well-priced or reliable.";
  }
  if (/\bfuture proof\b/.test(text)) {
    return "\"Future proof\" has no measurable definition and cannot be answered as asked.";
  }
  return null;
}

function jobFromPhrasing(phrase: string): JobToBeDone | null {
  const text = phrase.toLowerCase();
  if (/\bfirst (pc|build)\b/.test(text)) return "build-first-pc";
  if (/\b(vs|versus|or|compared to)\b/.test(text)) return "choose-between-components";
  if (/\b(low fps|stutter|slow|why is my)\b/.test(text)) return "diagnose-poor-performance";
  if (/\b(fps|frame rate|frames)\b/.test(text)) return "estimate-fps";
  if (/\bupgrade\b/.test(text)) return "determine-upgrade-path";
  if (/\b(fit|compatible|compatibility|socket)\b/.test(text)) return "avoid-compatibility-mistake";
  if (/\b(what is|what does|explain|mean)\b/.test(text)) return "understand-confusing-concept";
  return null;
}

/**
 * Produce paraphrases for creative variation.
 *
 * Explicitly generated, explicitly frequency-null, and traceable to whatever
 * they were derived from. These may be used to vary a hook; they may not be
 * used to claim that anybody phrases the problem this way.
 */
export function generateParaphrases(
  base: string,
  rationale: string,
  variants: readonly string[],
): readonly GeneratedPhrase[] {
  return variants.map((phrase) => ({
    origin: "generated" as const,
    phrase,
    derivedFromPhrase: base,
    rationale,
    frequency: null,
  }));
}

/**
 * The terminology a creative must explain rather than assume.
 *
 * Terms appear here when they show up in observed language from an audience
 * whose expertise is beginner or unknown — i.e. exactly when we cannot show
 * that the audience already knows them.
 */
export function terminologyRequiringExplanation(
  phrases: readonly ObservedPhrase[],
): readonly string[] {
  const needing = new Set<string>();
  for (const phrase of phrases) {
    if (phrase.expertiseImplication === "advanced") continue;
    for (const term of phrase.terminology) needing.add(term);
  }
  return [...needing].sort();
}
