// The saved-take render path: it renders only the one paid take of run
// 37086531999, checked against GitHub before download and by audio hash after,
// and never asks the provider for anything.

import { describe, expect, it } from "vitest";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { GEORGE_VOICE_ID, REVIEWED_LIAM_VOICE } from "../liamVoice.ts";
import { APPROVED_RAM_FIT_LINES, lineTimingsFromAlignment, RAM_FIT_TAKE_AUDIO, RAM_FIT_TAKE_MANIFEST, RAM_FIT_TAKE_TEXT } from "./liamTake.ts";
import { renderModeFromArgs, takeForMode } from "./render.ts";
import { fakeAlignment } from "./testTake.ts";
import { assertSavedTake, SAVED_RAM_FIT_TAKE, verifySavedTakeRun } from "./savedTake.ts";

const TOKEN = "ghs_test_token_never_printed";

function github(over: { run?: Record<string, unknown>; jobs?: unknown[]; artifact?: Record<string, unknown>; status?: number } = {}) {
  const calls: { url: string; auth: string | null }[] = [];
  const fetchImpl = async (input: string, init?: RequestInit) => {
    calls.push({ url: input, auth: new Headers(init?.headers).get("authorization") });
    if (over.status) return new Response("{}", { status: over.status });
    const path = new URL(input).pathname;
    if (path.endsWith(`/actions/runs/${SAVED_RAM_FIT_TAKE.runId}`)) {
      return Response.json({ id: SAVED_RAM_FIT_TAKE.runId, head_sha: SAVED_RAM_FIT_TAKE.headSha, path: SAVED_RAM_FIT_TAKE.workflowPath, event: "workflow_dispatch", status: "completed", conclusion: "failure", ...over.run });
    }
    if (path.endsWith(`/actions/runs/${SAVED_RAM_FIT_TAKE.runId}/jobs`)) {
      return Response.json({ jobs: over.jobs ?? [
        { name: "sample", conclusion: "success", steps: [{ name: "Generate one Liam take of the RAM-fit pilot", conclusion: "success" }] },
        { name: "render-ram-fit", conclusion: "failure", steps: [] },
      ] });
    }
    if (path.endsWith(`/actions/artifacts/${SAVED_RAM_FIT_TAKE.artifactId}`)) {
      return Response.json({ id: SAVED_RAM_FIT_TAKE.artifactId, name: SAVED_RAM_FIT_TAKE.artifactName, expired: false, digest: SAVED_RAM_FIT_TAKE.artifactDigest, workflow_run: { id: SAVED_RAM_FIT_TAKE.runId }, ...over.artifact });
    }
    return new Response("{}", { status: 404 });
  };
  return { fetchImpl, calls };
}

describe("the saved take is pinned", () => {
  it("names the approved run, its commit, the generation step, the artifact and the Liam audio", () => {
    expect(SAVED_RAM_FIT_TAKE).toMatchObject({
      runId: 37086531999,
      headSha: "430d03cbc8338ce088f3f0d4d7394c1c0fde0d4b",
      artifactId: 11259988966,
      audioSha256: "ab54f7a9f57b3c6610d1a111fa3804d282f314be7f578318d5a033274ccdb871",
      voiceId: REVIEWED_LIAM_VOICE.voiceId,
    });
    expect(Object.isFrozen(SAVED_RAM_FIT_TAKE)).toBe(true);
  });
});

describe("checking the run before anything is downloaded", () => {
  it("accepts the pinned run, reading only GitHub's API with the job token", async () => {
    const { fetchImpl, calls } = github();
    const lines = await verifySavedTakeRun({ token: TOKEN, fetchImpl });
    expect(lines.join(" ")).toContain("37086531999");
    expect(calls.every((call) => call.url.startsWith(`https://api.github.com/repos/${SAVED_RAM_FIT_TAKE.repository}/`))).toBe(true);
    expect(calls.every((call) => call.auth === `Bearer ${TOKEN}`)).toBe(true);
    expect(lines.join(" ")).not.toContain(TOKEN);
  });

  it("refuses another commit, workflow, trigger, or an unfinished run", async () => {
    for (const run of [{ head_sha: "0".repeat(40) }, { path: ".github/workflows/verify-pr.yml" }, { event: "push" }, { status: "in_progress" }, { id: 1 }]) {
      await expect(verifySavedTakeRun({ token: TOKEN, ...github({ run }) })).rejects.toThrow(/Not rendered/);
    }
  });

  it("refuses a run whose take was not generated by the RAM-fit step", async () => {
    await expect(verifySavedTakeRun({ token: TOKEN, ...github({ jobs: [{ name: "sample", conclusion: "failure", steps: [] }] }) })).rejects.toThrow(/sample job did not succeed/);
    await expect(verifySavedTakeRun({ token: TOKEN, ...github({ jobs: [{ name: "sample", conclusion: "success", steps: [{ name: "Generate one Liam take of the GPU race draft", conclusion: "success" }] }] }) })).rejects.toThrow(/did not generate the RAM-fit take/);
    await expect(verifySavedTakeRun({ token: TOKEN, ...github({ jobs: [{ name: "sample", conclusion: "success", steps: [{ name: SAVED_RAM_FIT_TAKE.step, conclusion: "skipped" }] }] }) })).rejects.toThrow(/did not generate the RAM-fit take/);
  });

  it("refuses an artifact that is not the pinned one, from another run, expired, or with another digest", async () => {
    await expect(verifySavedTakeRun({ token: TOKEN, ...github({ artifact: { name: "specsmith-gpu-race-liam-take" } }) })).rejects.toThrow(/not the RAM-fit take of the pinned run/);
    await expect(verifySavedTakeRun({ token: TOKEN, ...github({ artifact: { workflow_run: { id: 1 } } }) })).rejects.toThrow(/not the RAM-fit take of the pinned run/);
    await expect(verifySavedTakeRun({ token: TOKEN, ...github({ artifact: { expired: true } }) })).rejects.toThrow(/expired/);
    await expect(verifySavedTakeRun({ token: TOKEN, ...github({ artifact: { digest: `sha256:${"0".repeat(64)}` } }) })).rejects.toThrow(/digest/);
  });

  it("refuses without a token or when GitHub refuses, and never echoes the token", async () => {
    await expect(verifySavedTakeRun({ token: undefined, ...github() })).rejects.toThrow(/No GitHub token/);
    const error = await verifySavedTakeRun({ token: TOKEN, ...github({ status: 403 }) }).catch((caught: Error) => caught);
    expect(String(error)).toMatch(/HTTP 403/);
    expect(String(error)).not.toContain(TOKEN);
  });
});

describe("checking the take after download", () => {
  it("accepts only the pinned audio in the pinned Liam voice", () => {
    expect(() => assertSavedTake({ voiceId: REVIEWED_LIAM_VOICE.voiceId, audioSha256: SAVED_RAM_FIT_TAKE.audioSha256 })).not.toThrow();
    expect(() => assertSavedTake({ voiceId: REVIEWED_LIAM_VOICE.voiceId, audioSha256: "0".repeat(64) })).toThrow(/not the saved take/);
    expect(() => assertSavedTake({ voiceId: GEORGE_VOICE_ID, audioSha256: SAVED_RAM_FIT_TAKE.audioSha256 })).toThrow(/not the pinned Liam voice/);
  });

  it("is a final render that must be asked for by name", () => {
    expect(renderModeFromArgs(["--saved-take", "some/dir"])).toMatchObject({ mode: "final", savedTake: true });
    expect(() => renderModeFromArgs(["--saved-take"])).toThrow(/needs the take directory/);
    expect(renderModeFromArgs(["--liam-take", "some/dir"])).not.toHaveProperty("savedTake");
  });
});

describe("the renderer's saved-take mode", () => {
  it("refuses a valid Liam take that is not the saved bytes, which --liam-take would accept", async () => {
    const dir = await mkdtemp(join(tmpdir(), "ram-fit-saved-"));
    try {
      const mp3Path = join(dir, "tone.mp3");
      execFileSync("ffmpeg", ["-loglevel", "error", "-f", "lavfi", "-i", "sine=frequency=220:duration=2", "-ar", "44100", "-ac", "1", "-b:a", "64k", mp3Path]);
      const mp3 = await readFile(mp3Path);
      const takeDir = join(dir, "take");
      await mkdir(takeDir);
      await writeFile(join(takeDir, RAM_FIT_TAKE_AUDIO), mp3);
      const alignment = fakeAlignment();
      await writeFile(join(takeDir, RAM_FIT_TAKE_MANIFEST), JSON.stringify({
        isFixture: false, voiceId: REVIEWED_LIAM_VOICE.voiceId, voiceUsed: "Liam", modelId: "m", text: RAM_FIT_TAKE_TEXT, lines: APPROVED_RAM_FIT_LINES,
        audio: { file: RAM_FIT_TAKE_AUDIO, bytes: mp3.byteLength, sha256: createHash("sha256").update(mp3).digest("hex") },
        lineTimings: lineTimingsFromAlignment(alignment), alignment, alignmentError: null, providerReportedCharacterCost: null,
      }));
      await expect(takeForMode({ mode: "final", takeDir })).resolves.toMatchObject({ voiceId: REVIEWED_LIAM_VOICE.voiceId });
      await expect(takeForMode({ mode: "final", takeDir, savedTake: true })).rejects.toThrow(/not the saved take/);
      await expect(takeForMode({ mode: "draft" })).resolves.toBeNull();
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });
});
